# Generated by Django 5.1.1 on 2024-09-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='Title',
        ),
        migrations.AddField(
            model_name='advert',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
